[package]
name = "flashqc-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
diesel = {version = "2.3.3", features = ["postgres", "uuid", "serde_json"]}
dotenvy = "0.15.7"
rocket = "0.5.1"
serde = {version="1.0.219", features=["derive"]}
serde_json = "1.0.143"
uuid = "1.18.0"
